[project]
name = "coffeeoracle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotfile>=0.9.0",
    "openai>=2.16.0",
    "python-dotenv>=1.2.1",
    "reflex>=0.8.26",
]
